"""
skill_autogpt_forge.py -- AutoGPT Forge Agent开发框架骨髓内化

骨髓内化来源: AutoGPT Forge (Significant-Gravitas, 184k⭐)
原始模块: forge/ (Agent开发脚手架/模板系统)

设计哲学(用自己的话重建):
  Forge不是"框架"----它是Agent开发的"反应堆"。
  核心思想:Agent = 骨架(Forge) + 能力(Plugin) + 配置(Config)。
  你不用写Agent,你只是组装它。Forge负责所有通用基础设施,
  你只需要关心你的Agent"与众不同"的那部分。

骨架(GA嫁接点):
  ① AgentConfig -- 配置模型(YAML/JSON/Env)
  ② AgentTemplate -- Agent骨架模板生成器
  ③ ComponentRegistry -- 组件注册表(LLM/Tool/Memory/...)
  ④ AgentBuilder -- Builder模式构建Agent
  ⑤ ConfigValidator -- 配置校验
  ⑥ PluginSystem -- 插件加载/热插拔
  ⑦ AgentProfile -- Agent配置描述符
  ⑧ connect_to_ga -- GA嫁接器
"""

import json
import os
import hashlib
import inspect
import importlib
from typing import Dict, List, Optional, Any, Callable, Tuple, Union
from dataclasses import dataclass, field, asdict
from enum import Enum, auto
import yaml
import datetime


# ═══════════════════════════════════════════════════
# ① AgentConfig -- 配置模型
# ═══════════════════════════════════════════════════

@dataclass
class LLMConfig:
    """LLM配置"""
    provider: str = "openai"
    model: str = "gpt-4"
    temperature: float = 0.7
    max_tokens: int = 4096
    api_key_env: str = "OPENAI_API_KEY"
    base_url: Optional[str] = None

@dataclass
class AgentConfig:
    """完整的Agent配置"""
    name: str = "GA_Agent"
    version: str = "0.1.0"
    description: str = ""
    author: str = "GA"
    
    # 组件配置
    llm: LLMConfig = field(default_factory=LLMConfig)
    tools: List[str] = field(default_factory=list)
    memory: Dict[str, Any] = field(default_factory=dict)
    
    # 运行配置
    max_iterations: int = 50
    timeout: int = 300
    verbose: bool = False
    max_concurrency: int = 1
    
    # 插件
    plugins: List[str] = field(default_factory=list)
    
    # 定制
    system_prompt: str = "You are a helpful AI assistant."
    extra: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return asdict(self)
    
    def to_yaml(self) -> str:
        return yaml.dump(asdict(self), default_flow_style=False)
    
    @classmethod
    def from_dict(cls, data: Dict) -> "AgentConfig":
        if "llm" in data and isinstance(data["llm"], dict):
            data["llm"] = LLMConfig(**data["llm"])
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})
    
    @classmethod
    def from_yaml(cls, path: str) -> "AgentConfig":
        with open(path, 'r') as f:
            data = yaml.safe_load(f)
        return cls.from_dict(data)
    
    @classmethod
    def from_env(cls, prefix: str = "AGENT_") -> "AgentConfig":
        """从环境变量读取配置"""
        import os as _os
        cfg = cls()
        for field_name in cls.__dataclass_fields__:
            env_key = f"{prefix}{field_name.upper()}"
            if env_key in _os.environ:
                setattr(cfg, field_name, _os.environ[env_key])
        return cfg


# ═══════════════════════════════════════════════════
# ② AgentTemplate -- 骨架模板生成器
# ═══════════════════════════════════════════════════

class AgentTemplate:
    """Agent骨架模板生成器 -- 类似create-react-app的scaffold"""
    
    @staticmethod
    def _base_template(name, class_name, description):
        lines = []
        lines.append('"""')
        lines.append(f"{name} -- AutoGPT Agent (Generated by Forge)")
        lines.append('"""')
        lines.append("from typing import Dict, Any, Optional")
        lines.append("import json")
        lines.append("")
        lines.append(f"class {class_name}:")
        lines.append('    """' + description + '"""')
        lines.append("    ")
        lines.append('    def __init__(self, config: Optional[Dict[str, Any]] = None):')
        lines.append("        self.config = config or {}")
        lines.append(f'        self.name = "{name}"')
        lines.append("        self.memory: Dict[str, Any] = {}")
        lines.append("        ")
        lines.append('    def run(self, task: str) -> str:')
        lines.append('        """execute task"""')
        lines.append('        return f"{self.name} processed: {task}"')
        lines.append("    ")
        lines.append('    def save_state(self, path: str) -> None:')
        lines.append('        with open(path, "w") as f:')
        lines.append('            json.dump({"name": self.name, "memory": self.memory}, f)')
        lines.append("    ")
        lines.append('    @classmethod')
        lines.append(f'    def load_state(cls, path: str) -> "{class_name}":')
        lines.append("        with open(path) as f:")
        lines.append("            data = json.load(f)")
        lines.append("        agent = cls()")
        lines.append('        agent.memory = data.get("memory", {})')
        lines.append("        return agent")
        return "\n".join(lines)
    
    @classmethod
    def scaffold(cls, name: str, output_dir: str, 
                 description: str = "AutoGPT Agent",
                 include_tests: bool = True) -> str:
        """生成Agent骨架"""
        class_name = "".join(word.capitalize() for word in name.replace("-", "_").split("_"))
        
        # 生成主文件
        code = cls._base_template(name, class_name, description)
        
        os.makedirs(output_dir, exist_ok=True)
        main_path = os.path.join(output_dir, f"{name}.py")
        with open(main_path, "w") as f:
            f.write(code)
        
        # 生成配置文件
        config = AgentConfig(name=name, description=description)
        config_path = os.path.join(output_dir, f"{name}_config.yaml")
        with open(config_path, "w") as f:
            f.write(config.to_yaml())
        
        # 生成测试骨架
        if include_tests:
            test_lines = []
            test_lines.append('"""')
            test_lines.append(f"Tests for {name}")
            test_lines.append('"""')
            test_lines.append(f"from {name} import {class_name}")
            test_lines.append("")
            test_lines.append(f"def test_{name}_basic():")
            test_lines.append(f"    agent = {class_name}()")
            test_lines.append('    result = agent.run("hello")')
            test_lines.append('    assert "processed" in result')
            test_lines.append("")
            test_lines.append(f"def test_{name}_save_load(tmpdir):")
            test_lines.append(f"    agent = {class_name}()")
            test_lines.append('    path = tmpdir / "state.json"')
            test_lines.append("    agent.save_state(str(path))")
            test_lines.append("    assert path.exists()")
            test_lines.append(f"    loaded = {class_name}.load_state(str(path))")
            test_lines.append("    assert loaded.name == agent.name")
            test_code = "\n".join(test_lines)
            
            test_dir = os.path.join(output_dir, "tests")
            os.makedirs(test_dir, exist_ok=True)
            test_path = os.path.join(test_dir, f"test_{name}.py")
            with open(test_path, "w") as f:
                f.write(test_code)
        
        return main_path


# ═══════════════════════════════════════════════════
# ③ ComponentRegistry -- 组件注册表
# ═══════════════════════════════════════════════════

class ComponentType(Enum):
    LLM = auto()
    TOOL = auto()
    MEMORY = auto()
    PLUGIN = auto()
    EVALUATOR = auto()
    PROMPT = auto()

@dataclass
class Component:
    """注册的组件"""
    name: str
    type: ComponentType
    factory: Callable
    version: str = "0.1.0"
    description: str = ""
    tags: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    
    def create(self, **kwargs) -> Any:
        return self.factory(**kwargs)

class ComponentRegistry:
    """组件注册表 -- 类似Spring的IoC容器轻量版"""
    
    def __init__(self):
        self._components: Dict[str, Component] = {}
    
    def register(self, component: Component) -> None:
        key = f"{component.type.name.lower()}:{component.name}"
        self._components[key] = component
    
    def register_class(self, cls: type, type_: ComponentType, 
                       name: Optional[str] = None) -> Component:
        name = name or cls.__name__.lower()
        component = Component(
            name=name,
            type=type_,
            factory=cls,
            description=cls.__doc__ or ""
        )
        self.register(component)
        return component
    
    def get(self, type_: ComponentType, name: str) -> Optional[Component]:
        return self._components.get(f"{type_.name.lower()}:{name}")
    
    def create(self, type_: ComponentType, name: str, **kwargs) -> Any:
        comp = self.get(type_, name)
        if comp is None:
            raise KeyError(f"Component not found: {type_.name}/{name}")
        return comp.create(**kwargs)
    
    def list_by_type(self, type_: ComponentType) -> List[Component]:
        prefix = f"{type_.name.lower()}:"
        return [c for k, c in self._components.items() if k.startswith(prefix)]
    
    def search(self, query: str) -> List[Component]:
        q = query.lower()
        return [c for c in self._components.values() 
                if q in c.name.lower() or q in c.description.lower()]
    
    @property
    def count(self) -> int:
        return len(self._components)


# ═══════════════════════════════════════════════════
# ④ AgentBuilder -- Builder模式
# ═══════════════════════════════════════════════════

class AgentBuilder:
    """Builder模式构建Agent -- 链式调用"""
    
    def __init__(self, name: str = "GA_Agent"):
        self._config = AgentConfig(name=name)
        self._components: Dict[str, Any] = {}
        self._plugins: List[Any] = []
    
    def with_llm(self, provider: str = "openai", model: str = "gpt-4",
                 **kwargs) -> "AgentBuilder":
        self._config.llm = LLMConfig(provider=provider, model=model, **kwargs)
        return self
    
    def with_tool(self, tool_name: str) -> "AgentBuilder":
        self._config.tools.append(tool_name)
        return self
    
    def with_memory(self, memory_type: str = "basic", **kwargs) -> "AgentBuilder":
        self._config.memory = {"type": memory_type, **kwargs}
        return self
    
    def with_plugin(self, plugin_path: str) -> "AgentBuilder":
        self._config.plugins.append(plugin_path)
        return self
    
    def with_system_prompt(self, prompt: str) -> "AgentBuilder":
        self._config.system_prompt = prompt
        return self
    
    def with_config(self, config: AgentConfig) -> "AgentBuilder":
        self._config = config
        return self
    
    def build(self) -> Dict[str, Any]:
        """构建完成,返回配置和组件快照"""
        return {
            "config": self._config,
            "components": self._components,
            "plugins": self._plugins,
            "profile": AgentProfile(
                name=self._config.name,
                version=self._config.version,
                capabilities=self._config.tools + list(self._components.keys()),
                config_hash=hashlib.md5(
                    json.dumps(self._config.to_dict(), sort_keys=True).encode()
                ).hexdigest()[:12]
            )
        }


# ═══════════════════════════════════════════════════
# ⑤ ConfigValidator -- 配置校验
# ═══════════════════════════════════════════════════

@dataclass
class ValidationError:
    field: str
    message: str
    severity: str = "error"  # error / warning / info

class ConfigValidator:
    """配置校验器"""
    
    RULES = {
        "name": lambda v: (len(v) > 0, "Name cannot be empty"),
        "max_iterations": lambda v: (1 <= v <= 10000, "max_iterations must be 1-10000"),
        "timeout": lambda v: (v > 0, "timeout must be positive"),
        "max_concurrency": lambda v: (v >= 1, "max_concurrency must be >= 1"),
    }
    
    @classmethod
    def validate(cls, config: AgentConfig) -> List[ValidationError]:
        errors = []
        for field, rule in cls.RULES.items():
            if hasattr(config, field):
                ok, msg = rule(getattr(config, field))
                if not ok:
                    errors.append(ValidationError(field=field, message=msg))
        return errors
    
    @classmethod
    def validate_yaml(cls, path: str) -> Tuple[bool, List[ValidationError]]:
        try:
            config = AgentConfig.from_yaml(path)
            errors = cls.validate(config)
            return len(errors) == 0, errors
        except Exception as e:
            return False, [ValidationError(field="file", message=str(e))]


# ═══════════════════════════════════════════════════
# ⑥ PluginSystem -- 插件系统
# ═══════════════════════════════════════════════════

class PluginBase:
    """插件基类"""
    name: str = ""
    version: str = "0.1.0"
    description: str = ""
    
    def on_load(self) -> None: ...
    def on_unload(self) -> None: ...
    def on_before_run(self, task: str) -> str: return task
    def on_after_run(self, result: str) -> str: return result

class PluginSystem:
    """插件加载/热插拔系统"""
    
    def __init__(self):
        self._plugins: Dict[str, PluginBase] = {}
        self._hooks: Dict[str, List[str]] = {}  # hook_name -> [plugin_names]
    
    def load(self, plugin_path: str) -> Optional[PluginBase]:
        """动态加载插件"""
        try:
            spec = importlib.util.spec_from_file_location(
                f"plugin_{hash(plugin_path)}", plugin_path
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            
            # 查找PluginBase子类
            for attr_name in dir(mod):
                attr = getattr(mod, attr_name)
                if isinstance(attr, type) and issubclass(attr, PluginBase) and attr is not PluginBase:
                    plugin = attr()
                    self._plugins[plugin.name] = plugin
                    self._register_hooks(plugin)
                    plugin.on_load()
                    return plugin
        except Exception as e:
            print(f"Plugin load error ({plugin_path}): {e}")
        return None
    
    def _register_hooks(self, plugin: PluginBase) -> None:
        for hook_name in ["on_before_run", "on_after_run"]:
            method = getattr(plugin, hook_name, None)
            if method and method.__func__ is not getattr(PluginBase, hook_name):
                self._hooks.setdefault(hook_name, []).append(plugin.name)
    
    def unload(self, name: str) -> bool:
        plugin = self._plugins.pop(name, None)
        if plugin:
            plugin.on_unload()
            for hooks in self._hooks.values():
                if name in hooks:
                    hooks.remove(name)
            return True
        return False
    
    def execute_hook(self, hook_name: str, *args, **kwargs) -> Any:
        result = args[0] if args else kwargs.get("task", "")
        for plugin_name in self._hooks.get(hook_name, []):
            plugin = self._plugins.get(plugin_name)
            if plugin:
                hook_func = getattr(plugin, hook_name)
                result = hook_func(result)
        return result
    
    @property
    def loaded_count(self) -> int:
        return len(self._plugins)


# ═══════════════════════════════════════════════════
# ⑦ AgentProfile -- Agent配置描述符
# ═══════════════════════════════════════════════════

@dataclass
class AgentProfile:
    name: str
    version: str
    capabilities: List[str]
    config_hash: str
    created_at: str = field(default_factory=lambda: datetime.datetime.now().isoformat())
    
    def to_dict(self) -> Dict:
        return asdict(self)
    
    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)
    
    @classmethod
    def from_build(cls, builder: AgentBuilder) -> "AgentProfile":
        build = builder.build()
        return build["profile"]


# ═══════════════════════════════════════════════════
# ⑧ connect_to_ga -- GA嫁接
# ═══════════════════════════════════════════════════

def connect_to_ga() -> Dict[str, Any]:
    """将AutoGPT Forge嫁接到GA生态"""
    
    installed = []
    
    # 注册到skill_registry
    try:
        from skill_registry import register_system_skill
        register_system_skill(
            "skill_autogpt_forge",
            ["forgebuilder", "agentscaffold", "pluginloader"],
            "AutoGPT Forge Agent开发框架骨髓内化"
        )
        installed.append("skill_registry")
    except ImportError:
        pass
    
    # 安装为GA插件(GStack)
    try:
        from skill_gstack import install_skill_as_plugin
        install_skill_as_plugin(
            "autogpt_forge",
            {
                "AgentConfig": AgentConfig,
                "AgentBuilder": AgentBuilder,
                "ComponentRegistry": ComponentRegistry,
                "PluginSystem": PluginSystem,
                "AgentTemplate": AgentTemplate,
            }
        )
        installed.append("gstack")
    except ImportError:
        pass
    
    return {
        "module": "skill_autogpt_forge",
        "components": ["AgentConfig", "AgentBuilder", "ComponentRegistry",
                       "PluginSystem", "AgentTemplate", "ConfigValidator"],
        "status": "mounted",
        "installed_to": installed or ["standalone"]
    }


# ═══════════════════════════════════════════════════
# ✅ 自检
# ═══════════════════════════════════════════════════

def self_check() -> Dict[str, bool]:
    """运行8项自检"""
    checks = {
        "AgentConfig(配置模型)": False,
        "AgentTemplate(骨架生成)": False,
        "ComponentRegistry(组件注册)": False,
        "AgentBuilder(Builder模式)": False,
        "ConfigValidator(校验器)": False,
        "PluginSystem(插件系统)": False,
        "AgentProfile(描述符)": False,
        "connect_to_ga(GA嫁接)": False,
    }
    
    try:
        # 1. AgentConfig
        cfg = AgentConfig(name="test_agent")
        assert cfg.name == "test_agent"
        d = cfg.to_dict()
        assert "name" in d
        cfg2 = AgentConfig.from_dict(d)
        assert cfg2.name == cfg.name
        y = cfg.to_yaml()
        assert "test_agent" in y
        checks["AgentConfig(配置模型)"] = True
    except:
        pass
    
    try:
        # 2. AgentTemplate
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            path = AgentTemplate.scaffold("my_agent", tmpdir, "Test Agent")
            assert os.path.exists(path)
            config_path = os.path.join(tmpdir, "my_agent_config.yaml")
            assert os.path.exists(config_path)
            test_path = os.path.join(tmpdir, "tests", "test_my_agent.py")
            assert os.path.exists(test_path)
        checks["AgentTemplate(骨架生成)"] = True
    except:
        pass
    
    try:
        # 3. ComponentRegistry
        reg = ComponentRegistry()
        reg.register(Component("test_tool", ComponentType.TOOL, lambda: "tool"))
        assert reg.count == 1
        comp = reg.get(ComponentType.TOOL, "test_tool")
        assert comp is not None
        assert comp.create() == "tool"
        result = reg.list_by_type(ComponentType.TOOL)
        assert len(result) == 1
        checks["ComponentRegistry(组件注册)"] = True
    except:
        pass
    
    try:
        # 4. AgentBuilder
        builder = AgentBuilder("test_builder")
        builder.with_llm("openai", "gpt-4").with_tool("web_search")
        build = builder.build()
        assert build["config"].name == "test_builder"
        assert "web_search" in build["config"].tools
        assert "config_hash" in build["profile"].to_dict()
        checks["AgentBuilder(Builder模式)"] = True
    except:
        pass
    
    try:
        # 5. ConfigValidator
        cfg = AgentConfig(name="", max_iterations=0)
        errors = ConfigValidator.validate(cfg)
        assert len(errors) >= 2
        assert any(e.field == "name" for e in errors)
        checks["ConfigValidator(校验器)"] = True
    except:
        pass
    
    try:
        # 6. PluginSystem
        ps = PluginSystem()
        assert ps.loaded_count == 0
        
        class TestPlugin(PluginBase):
            name = "test_plugin"
            version = "1.0"
            
            def on_before_run(self, task):
                return f"plugin({task})"
        
        tp = TestPlugin()
        ps._plugins[tp.name] = tp
        ps._register_hooks(tp)
        assert ps.loaded_count == 1
        result = ps.execute_hook("on_before_run", "hello")
        assert result == "plugin(hello)"
        checks["PluginSystem(插件系统)"] = True
    except:
        pass
    
    try:
        # 7. AgentProfile
        profile = AgentProfile(name="p1", version="1.0", 
                              capabilities=["tool1"], config_hash="abc123")
        d = profile.to_dict()
        assert d["name"] == "p1"
        j = profile.to_json()
        assert '"name": "p1"' in j
        checks["AgentProfile(描述符)"] = True
    except:
        pass
    
    try:
        # 8. connect_to_ga
        result = connect_to_ga()
        assert result["module"] == "skill_autogpt_forge"
        assert len(result["components"]) == 6
        checks["connect_to_ga(GA嫁接)"] = True
    except:
        pass
    
    return checks


if __name__ == "__main__":
    results = self_check()
    passed = sum(1 for v in results.values() if v)
    total = len(results)
    print(f"=== skill_autogpt_forge.py 自检 [{passed}/{total}] ===")
    for k, v in results.items():
        print(f"  {'✅' if v else '❌'} {k}")
