"""
skill_on_demand_data.py — P8 按需调度器技能数据集
包含所有已内化技能的核心描述/标签/场景/模块名
与 skill_on_demand_scheduler.py 数据逻辑分离
"""

ALL_SKILLS = {
    "agency_agents": {
        "core": '103.4k⭐全栈AI Agency，非技术用户一键AI团队，TypeScript+Prompt模板',
        "tags": ['agent', '全栈', '开箱即用', '团队协作'],
        "scenes": ['非技术用户使用AI', '全栈AI团队'],
        "module": 'skill_agency_agents',
    },
    "agent_reach": {
        "core": '20k⭐ Agent互联网眼睛/推特/Reddit/小红书',
        "tags": ['agent', '互联网', '社交', 'MCP'],
        "scenes": ['互联网信息获取'],
        "module": 'skill_agent_reach',
    },
    "agentmem": {
        "core": 'Agent记忆信任治理/5态生命周期/冲突检测',
        "tags": ['memory', '记忆', '治理', '信任'],
        "scenes": ['记忆治理'],
        "module": 'skill_agentmem',
    },
    "ai_agent_ecosystem": {
        "core": 'AI Agent开源生态速览/Top7/hermes-agent',
        "tags": ['AI', 'agent', '生态', '开源'],
        "scenes": ['AI Agent生态'],
        "module": 'skill_ai_agent_ecosystem',
    },
    "ai_agent_era_map": {
        "core": 'AI Agent真实生态图/光明面+黑暗面+思考',
        "tags": ['AI', 'agent', '生态', '分析'],
        "scenes": ['AI生态分析', 'Agent趋势'],
        "module": 'skill_ai_agent_era_map',
    },
    "aristotle_perspective": {
        "core": '逻辑奠基者/观察优先/本质在此岸',
        "tags": ['思维', '哲学', '亚里士多德', '逻辑'],
        "scenes": ['逻辑推理', '本质分析'],
        "module": 'skill_aristotle_perspective',
    },
    "astrbot_analysis": {
        "core": 'AstrBot 32.5k⭐架构/MCP stdio白名单',
        "tags": ['agent', '架构', 'MCP', '沙箱'],
        "scenes": ['AstrBot架构分析'],
        "module": 'skill_astrbot_analysis',
    },
    "awesome_design_md": {
        "core": '81k⭐ DESIGN.md设计系统/vibe design',
        "tags": ['设计', 'DESIGN.md', '系统', '文档'],
        "scenes": ['设计系统文档'],
        "module": 'skill_awesome_design_md',
    },
    "billd_desk": {
        "core": '6.7k⭐ 开源远程桌面/WebRTC/Vue3',
        "tags": ['远程桌面', 'WebRTC', 'Vue3', '跨平台'],
        "scenes": ['远程桌面方案'],
        "module": 'skill_billd_desk',
    },
    "board_perspectives": {
        "core": '13位大佬思维全览：芒格/达利欧/贝佐斯/马克斯/索罗斯/Karpathy',
        "tags": ['思维', '投资', '大佬', '多视角'],
        "scenes": ['多角度分析问题'],
        "module": 'skill_board_perspectives',
    },
    "board_perspectives_deep": {
        "core": '13思维矩阵+GA Agentic Protocol+12实战',
        "tags": ['思维', '矩阵', 'GA', '实战'],
        "scenes": ['多视角分析', '思维矩阵'],
        "module": 'skill_board_perspectives_deep',
    },
    "browser_use": {
        "core": '94.8k⭐ 骨髓级/源码解构/双模感知',
        "tags": ['baidu', 'MCP', '打开', '自动化', '搜索', '访问', '浏览器', '百度', 'google', 'agent', 'open'],
        "scenes": ['打开网站', '浏览器自动化', '访问URL', '百度搜索', '网页自动化'],
        "module": 'skill_browser_use',
    },
    "chroma": {
        "core": '嵌入式向量数据库/28k⭐/4函数API',
        "tags": ['数据库', '向量', '嵌入', 'RAG'],
        "scenes": ['向量数据库'],
        "module": 'skill_chroma',
    },
    "claude_architecture_comparison": {
        "core": 'Claude完整架构/硬参数/P1-P6/6维矩阵',
        "tags": ['claude', '架构', '对比', '推理'],
        "scenes": ['理解Claude架构', '模型对比分析'],
        "module": 'skill_claude_architecture_comparison',
    },
    "claude_code_best_practice": {
        "core": '54k⭐ Claude Code最佳实践/Skills/MCP',
        "tags": ['claude', 'code', '最佳实践', 'MCP'],
        "scenes": ['Claude Code实践'],
        "module": 'skill_claude_code_best_practice',
    },
    "claude_code_skill": {
        "core": 'MCP控制Claude Code',
        "tags": ['MCP', 'claude', 'code', '控制'],
        "scenes": ['控制Claude Code'],
        "module": 'skill_claude_code_skill',
    },
    "claude_memory": {
        "core": 'thedotmack/claude-mem/77k⭐/5Hook体系/混合搜索',
        "tags": ['memory', 'claude', '记忆', '搜索'],
        "scenes": ['Claude记忆系统', '混合搜索'],
        "module": 'skill_claude_memory',
    },
    "claude_token_efficient": {
        "core": '指令压缩优化/10规则省63%Token',
        "tags": ['claude', '优化', 'token', '压缩'],
        "scenes": ['指令压缩优化'],
        "module": 'skill_claude_token_efficient',
    },
    "cognitive_memory": {
        "core": '四层记忆+衰减模型',
        "tags": ['GA', '记忆', '衰减', '模型'],
        "scenes": ['记忆管理', '记忆衰减'],
        "module": 'skill_cognitive_memory',
    },
    "context_message_analyzer": {
        "core": 'P1-P6 MessageAnalyzer/ContextReport注入',
        "tags": ['GA', '上下文', '分析', '注入'],
        "scenes": ['GA上下文分析'],
        "module": 'skill_context_message_analyzer',
    },
    "core_context_v3_addon": {
        "core": 'v3增量模块4大能力注入',
        "tags": ['GA', '上下文', '增量', '注入'],
        "scenes": ['GA上下文扩展'],
        "module": 'skill_core_context_v3_addon',
    },
    "cowagent": {
        "core": '44.6k⭐微信/飞书/钉钉多平台Agent，三层次记忆+知识图谱+Skill Hub',
        "tags": ['飞书', 'IM', '钉钉', '知识图谱', '微信', 'agent', '多平台', 'wechat', 'robot', '机器人'],
        "scenes": ['接入企业微信', '多平台Agent部署', '构建微信机器人', '飞书集成', '接入微信机器人'],
        "module": 'skill_cowagent',
    },
    "dalio_perspective": {
        "core": '机器化思维/大周期',
        "tags": ['思维', '投资', '达利欧', '周期'],
        "scenes": ['大周期分析', '机器化思维'],
        "module": 'skill_dalio_perspective',
    },
    "data_analysis": {
        "core": '数据分析/Pandas/SQL/可视化/统计洞察',
        "tags": ['数据分析', '可视化', 'pandas', 'SQL', '统计'],
        "scenes": ['数据处理', '数据可视化', '数据分析报告'],
        "module": 'skill_data_analysis',
    },
    "design_pattern_hybrid_search": {
        "core": 'RRF混合搜索/49行/多源排序融合',
        "tags": ['设计模式', '搜索', '排序', '融合'],
        "scenes": ['混合搜索设计'],
        "module": 'skill_design_pattern_hybrid_search',
    },
    "design_pattern_incremental_index": {
        "core": '增量索引子图提取/SHA256/50x加速',
        "tags": ['设计模式', '索引', '增量', 'SHA'],
        "scenes": ['增量索引设计'],
        "module": 'skill_design_pattern_incremental_index',
    },
    "design_pattern_mcp_self_guided": {
        "core": 'MCP自引导NextStepHints/38行/零侵入',
        "tags": ['设计模式', 'MCP', '引导', '优化'],
        "scenes": ['MCP自引导设计'],
        "module": 'skill_design_pattern_mcp_self_guided',
    },
    "docker_devops": {
        "core": 'Docker容器化/CI-CD/DevOps流水线/K8s编排',
        "tags": ['Docker', 'DevOps', '容器', 'CI-CD'],
        "scenes": ['Docker部署', 'CI-CD流水线', '容器化'],
        "module": 'skill_docker_devops',
    },
    "easyocr_sop": {
        "core": 'EasyOCR文字识别工具：图片文字提取/OCR识别/多语言支持',
        "tags": ['OCR', '识别', '图片', '文字', 'easyocr', '文字识别', 'image', 'text'],
        "scenes": ['图片文字识别', 'OCR识别', '提取图片文字'],
        "module": 'easyocr_sop',
    },
    "ecom_content": {
        "core": '电商内容助手：3能力+8维合规+可执行脚本',
        "tags": ['电商', '内容', '合规', '营销'],
        "scenes": ['写电商文案', '合规检查'],
        "module": 'skill_ecom_content',
    },
    "ecom_ops": {
        "core": '电商运营5包：选品6标准+私域SOP+万相台测款+OZON选品',
        "tags": ['电商', '运营', '选品', '私域'],
        "scenes": ['电商运营决策', '选品分析'],
        "module": 'skill_ecom_ops',
    },
    "fastmcp": {
        "core": '25.2k⭐ FastMCP Pythonic框架，@mcp.tool装饰器，零配置',
        "tags": ['MCP', 'fastmcp', 'python'],
        "scenes": ['快速搭建MCP Server'],
        "module": 'skill_fastmcp',
    },
    "ga_frontends": {
        "core": 'GA前端层32文件700KB/FastAPI网关+桌面桥',
        "tags": ['GA', '前端', '网关', 'IM'],
        "scenes": ['GA前端层'],
        "module": 'skill_ga_frontends',
    },
    "ga_mcp_server": {
        "core": 'GA通用MCP桥接层：FastMCP装饰器+双端+NextStepHint',
        "tags": ['GA', 'MCP', '桥接'],
        "scenes": ['GA与MCP互通'],
        "module": 'ga_mcp_server',
    },
    "ga_mcp_server_v2": {
        "core": 'GA通用MCP桥接层/P1/FastMCP装饰器',
        "tags": ['GA', 'MCP', '桥接', 'server'],
        "scenes": ['GA MCP桥接'],
        "module": 'skill_ga_mcp_server_v2',
    },
    "ga_orchestrate": {
        "core": 'GA编排引擎：StateGraph图式编排+Checkpoint+AgentRole',
        "tags": ['GA', '编排', '图', '状态管理'],
        "scenes": ['编排GA Agent'],
        "module": 'ga_orchestrate',
    },
    "ga_orchestrate_v1": {
        "core": 'GA Agent编排引擎/P4/StateGraph+Checkpoint',
        "tags": ['GA', '编排', '图', '状态'],
        "scenes": ['GA编排引擎'],
        "module": 'skill_ga_orchestrate_v1',
    },
    "ga_reflect_system": {
        "core": 'GA反射系统：Scheduler+Goal Mode+BBS，互斥运行+budget自驱',
        "tags": ['GA', '反射', '调度', '预算'],
        "scenes": ['GA后台任务调度'],
        "module": 'ga_reflect_system',
    },
    "ga_self_improve": {
        "core": 'GA自改进闭环：WAL+反思+技能创建+跨会话检索',
        "tags": ['GA', '自改进', '反思', 'WAL'],
        "scenes": ['GA自我进化'],
        "module": 'ga_self_improve',
    },
    "ga_self_improve_v1": {
        "core": 'GA自改进闭环/P3/WAL+反思+技能创建',
        "tags": ['GA', '自改进', '反思', 'WAL'],
        "scenes": ['GA自改进'],
        "module": 'skill_ga_self_improve_v1',
    },
    "ga_tool_executor": {
        "core": 'GA工具执行引擎：ToolRegistry注册式动作+双模感知+ActionLoop',
        "tags": ['GA', '工具', '执行', '动作'],
        "scenes": ['注册GA工具', '执行循环'],
        "module": 'ga_tool_executor',
    },
    "ga_tool_executor_v1": {
        "core": 'GA工具执行引擎/P5/ToolRegistry+双模感知',
        "tags": ['GA', '工具', '执行', '动作'],
        "scenes": ['GA工具执行'],
        "module": 'skill_ga_tool_executor_v1',
    },
    "geeker_admin": {
        "core": 'Geeker-Admin Vue3后台框架/7指令库/ProTable',
        "tags": ['vue', '后台', '前端', 'admin'],
        "scenes": ['快速搭建后台', 'Vue3开发'],
        "module": 'skill_geeker_admin',
    },
    "gemini_cli": {
        "core": 'google-gemini 104.4k⭐官方AI Agent CLI',
        "tags": ['gemini', 'google', 'CLI', 'MCP'],
        "scenes": ['Gemini CLI使用'],
        "module": 'skill_gemini_cli',
    },
    "github_mcp_server": {
        "core": 'GitHub MCP Server/30k⭐/自动管理Git',
        "tags": ['MCP', 'GitHub', 'git', 'server'],
        "scenes": ['GitHub MCP集成'],
        "module": 'skill_github_mcp_server',
    },
    "gitnexus_knowledge_graph": {
        "core": 'MCP知识图谱代码智能',
        "tags": ['MCP', '知识图谱', '代码', '图'],
        "scenes": ['代码智能分析', '知识图谱查询'],
        "module": 'skill_gitnexus_knowledge_graph',
    },
    "graphiti": {
        "core": '时态知识图谱/26.3k⭐/实体-关系-事实',
        "tags": ['知识图谱', '图', '时态', 'MCP'],
        "scenes": ['时态知识图谱'],
        "module": 'skill_graphiti',
    },
    "ha_ha_xixi_collab": {
        "core": '哈哈元気AI↔嘻嘻GA协同/键盘流直连',
        "tags": ['协同', '哈哈', '嘻嘻', 'GA'],
        "scenes": ['哈哈嘻嘻协同'],
        "module": 'skill_ha_ha_xixi_collab',
    },
    "haystack": {
        "core": 'deepset.ai编排框架/25.3k⭐/Pipeline',
        "tags": ['框架', '编排', 'RAG', 'pipeline'],
        "scenes": ['RAG编排框架'],
        "module": 'skill_haystack',
    },
    "hermes_agent": {
        "core": '160k⭐自改进Agent：反思→技能创建→跨会话回忆→FTS5记忆',
        "tags": ['agent', '自改进', '记忆', '反思'],
        "scenes": ['构建自改进Agent', 'Agent记忆系统'],
        "module": 'skill_hermes_agent',
    },
    "howard_marks_perspective": {
        "core": '第二层思维/钟摆',
        "tags": ['思维', '投资', '马克斯', '第二层'],
        "scenes": ['第二层思维', '投资分析'],
        "module": 'skill_howard_marks_perspective',
    },
    "hybrid_memory_search_v2": {
        "core": 'GA四层记忆引擎/P2/Bigram+BM25+信任周期',
        "tags": ['GA', '记忆', '搜索', '引擎'],
        "scenes": ['GA记忆引擎'],
        "module": 'skill_hybrid_memory_search_v2',
    },
    "install_memory_powermem_full": {
        "core": 'PowerMem安装配置',
        "tags": ['安装', '配置', 'memory', 'PowerMem'],
        "scenes": ['安装PowerMem'],
        "module": 'skill_install_memory_powermem_full',
    },
    "jeff_bezos_perspective": {
        "core": '贝佐斯三角',
        "tags": ['思维', '商业', '贝佐斯', '战略'],
        "scenes": ['商业战略分析'],
        "module": 'skill_jeff_bezos_perspective',
    },
    "karpathy_autoresearch": {
        "core": 'Karpathy AI自治研究/3文件模型/program.md',
        "tags": ['karpathy', '自治', '研究', 'AI'],
        "scenes": ['AI自治研究'],
        "module": 'skill_karpathy_autoresearch',
    },
    "karpathy_build_nanogpt": {
        "core": 'Karpathy GPT从零构建/Git提交即大纲',
        "tags": ['karpathy', 'GPT', 'transformer', '教学'],
        "scenes": ['GPT从零构建'],
        "module": 'skill_karpathy_build_nanogpt',
    },
    "karpathy_char_rnn": {
        "core": 'Karpathy字符级RNN/LSTM/GRU/12k⭐',
        "tags": ['karpathy', 'RNN', 'LSTM', '教学'],
        "scenes": ['字符RNN实现'],
        "module": 'skill_karpathy_char_rnn',
    },
    "karpathy_convnetjs": {
        "core": 'Karpathy浏览器CNN框架/11k⭐/纯JS',
        "tags": ['karpathy', 'CNN', 'JS', '浏览器'],
        "scenes": ['浏览器CNN训练'],
        "module": 'skill_karpathy_convnetjs',
    },
    "karpathy_cryptos": {
        "core": 'Karpathy从零实现比特币/SHA-256/ECDSA',
        "tags": ['karpathy', '比特币', '加密', '教学'],
        "scenes": ['比特币实现'],
        "module": 'skill_karpathy_cryptos',
    },
    "karpathy_llm_council": {
        "core": 'Karpathy多LLM投票/3阶段/匿名互评',
        "tags": ['karpathy', 'LLM', '投票', '评估'],
        "scenes": ['多LLM评估'],
        "module": 'skill_karpathy_llm_council',
    },
    "karpathy_makemore": {
        "core": 'Karpathy自回归字符LM/bigram→Transformer',
        "tags": ['karpathy', 'LM', '自回归', '教学'],
        "scenes": ['字符语言模型'],
        "module": 'skill_karpathy_makemore',
    },
    "karpathy_master_framework": {
        "core": 'Karpathy思维框架/11章/50repos全览',
        "tags": ['karpathy', '框架', '思维', '汇总'],
        "scenes": ['Karpathy全集'],
        "module": 'skill_karpathy_master_framework',
    },
    "karpathy_micrograd": {
        "core": 'Karpathy 95行自动微分引擎/反向传播',
        "tags": ['karpathy', '微分', '反向传播', '教学'],
        "scenes": ['自动微分引擎'],
        "module": 'skill_karpathy_micrograd',
    },
    "karpathy_minbpe": {
        "core": 'Karpathy BPE分词器从零实现/4层教学',
        "tags": ['karpathy', 'BPE', '分词', '教学'],
        "scenes": ['分词器实现'],
        "module": 'skill_karpathy_minbpe',
    },
    "karpathy_nanochat": {
        "core": 'Karpathy nanochat/单旋钮/Benchmark驱动',
        "tags": ['karpathy', 'nanochat', '调参', 'benchmark'],
        "scenes": ['Karpathy nanochat学习'],
        "module": 'skill_karpathy_nanochat',
    },
    "karpathy_neuraltalk2": {
        "core": 'Karpathy图像描述/5.6k⭐/CNN+RNN',
        "tags": ['karpathy', '图像', '描述', '多模态'],
        "scenes": ['图像描述生成'],
        "module": 'skill_karpathy_neuraltalk2',
    },
    "karpathy_rendergit": {
        "core": 'Karpathy仓库→单页HTML/2.3k⭐',
        "tags": ['karpathy', 'HTML', '仓库', '工具'],
        "scenes": ['仓库转HTML'],
        "module": 'skill_karpathy_rendergit',
    },
    "kronos": {
        "core": '25k⭐金融语言基础模型/K线Tokenizer/AAAI2026',
        "tags": ['金融', 'LLM', 'K线', 'tokenizer'],
        "scenes": ['金融语言模型'],
        "module": 'skill_kronos',
    },
    "langgraph": {
        "core": '有状态Agent编排/32.5k⭐/持久化执行',
        "tags": ['agent', '编排', 'graph', '状态'],
        "scenes": ['有状态Agent编排'],
        "module": 'skill_langgraph',
    },
    "laozi_perspective": {
        "core": '知止不殆/道法自然/水之智慧/东西合璧',
        "tags": ['思维', '哲学', '老子', '东方'],
        "scenes": ['东方哲学思维'],
        "module": 'skill_laozi_perspective',
    },
    "learning_progress": {
        "core": '技能学习进度/585总包/15已吃透',
        "tags": ['学习', '进度', '技能', '管理'],
        "scenes": ['技能学习管理'],
        "module": 'skill_learning_progress',
    },
    "llama_cpp": {
        "core": '111k⭐ LLM推理C++实现/GGML/4层架构',
        "tags": ['LLM', '推理', 'C++', 'llama'],
        "scenes": ['LLM本地推理'],
        "module": 'skill_llama_cpp',
    },
    "lobster_agent_pack": {
        "core": '龙虾Agent工具全览',
        "tags": ['agent', '工具', 'lobster', '主动'],
        "scenes": ['使用Agent工具包'],
        "module": 'skill_lobster_agent_pack',
    },
    "lobster_proactive_agent_essence": {
        "core": 'Lobster主动Agent三支柱/WAL协议',
        "tags": ['agent', '主动', 'WAL', '自改进'],
        "scenes": ['主动Agent设计'],
        "module": 'skill_lobster_proactive_agent_essence',
    },
    "mckinsey_consultant": {
        "core": 'McKinsey V4：渐进式披露/3阶段9步/MECE/Hypothesis Tree',
        "tags": ['咨询', 'MECE', '假设驱动', '结构化'],
        "scenes": ['商业分析', '咨询方法论'],
        "module": 'skill_mckinsey_consultant',
    },
    "mcp_complete": {
        "core": 'MCP协议完整消化：USB-C架构，三大组件+三大能力，GA注入方案',
        "tags": ['MCP', '协议', '模型上下文', '工具'],
        "scenes": ['搭建MCP Server', '理解MCP协议'],
        "module": 'skill_mcp_complete',
    },
    "mcp_ecosystem": {
        "core": 'MCP生态全景/87.2k⭐awesome-mcp-servers',
        "tags": ['MCP', '生态', 'server', '工具'],
        "scenes": ['MCP生态工具'],
        "module": 'skill_mcp_ecosystem',
    },
    "mcp_from_jingyan": {
        "core": 'MCP协议笔记补充',
        "tags": ['MCP', '协议', '笔记'],
        "scenes": ['MCP协议学习'],
        "module": 'skill_mcp_from_jingyan',
    },
    "mem0": {
        "core": '56.2k⭐ AI Agent记忆层/混合搜索/多后端',
        "tags": ['memory', '记忆', '搜索', 'agent'],
        "scenes": ['Agent记忆层'],
        "module": 'skill_mem0',
    },
    "memora": {
        "core": 'MCP记忆服务器/FastMCP/文档碎片/LLM去重',
        "tags": ['MCP', '记忆', 'server', '去重'],
        "scenes": ['MCP记忆服务器'],
        "module": 'skill_memora',
    },
    "mempalace": {
        "core": 'MemPalace/52.5k⭐/AAAK Dialect/Hybrid Search',
        "tags": ['memory', '记忆', 'mempalace', '搜索'],
        "scenes": ['永久记忆系统'],
        "module": 'skill_mempalace',
    },
    "memu_memory_framework": {
        "core": 'memU三层内存框架',
        "tags": ['memory', '内存', '框架', 'memU'],
        "scenes": ['内存框架设计'],
        "module": 'skill_memu_memory_framework',
    },
    "ms_agent_framework": {
        "core": '10.6k⭐企业级Graph编排，节点-边-条件路由，Python+C#双语言',
        "tags": ['agent', '编排', '企业级', 'Graph'],
        "scenes": ['企业级Agent治理', 'Graph编排'],
        "module": 'skill_ms_agent_framework',
    },
    "multi_agent_dev_team": {
        "core": 'PM+Dev双Agent开发框架',
        "tags": ['agent', '开发', '团队', 'PM'],
        "scenes": ['双Agent开发', '团队协作开发'],
        "module": 'skill_multi_agent_dev_team',
    },
    "munger_deep": {
        "core": '误判心理学25条精读/P3安全链增强',
        "tags": ['思维', '心理', '芒格', '误判'],
        "scenes": ['心理误判分析', '安全增强'],
        "module": 'skill_munger_deep',
    },
    "munger_perspective": {
        "core": '多元思维/逆向思考',
        "tags": ['思维', '投资', '芒格', '逆向'],
        "scenes": ['多元思维模型', '逆向思考'],
        "module": 'skill_munger_perspective',
    },
    "nanobot": {
        "core": '42.8k⭐ 250KB超轻量Agent，npx一键启动，WebUI+长程Goal',
        "tags": ['agent', '轻量', '零配置', 'MCP'],
        "scenes": ['快速部署Agent', '最小化Agent'],
        "module": 'skill_nanobot',
    },
    "ocr_utils": {
        "core": 'OCR工具函数集：屏幕截图识别/窗口文字提取',
        "tags": ['OCR', '识别', '截图', '文字', 'image', 'screen'],
        "scenes": ['屏幕识别', '截图文字提取'],
        "module": 'ocr_utils',
    },
    "oh_my_openagent": {
        "core": '58.9k⭐ TUI原生Agent编排，多模型+3D节点图',
        "tags": ['agent', '编排', 'TUI', '多模型'],
        "scenes": ['可视化Agent编排', '多模型对话流'],
        "module": 'skill_oh_my_openagent',
    },
    "openai_whisper_asr": {
        "core": '本地语音转文字',
        "tags": ['语音', 'ASR', 'whisper', '离线'],
        "scenes": ['语音转文字', '本地语音识别'],
        "module": 'skill_openai_whisper_asr',
    },
    "openhuman_memory_tree": {
        "core": 'OpenHuman Memory Tree/3层自动采集/双模存储',
        "tags": ['memory', '记忆', '采集', '存储'],
        "scenes": ['记忆树架构'],
        "module": 'skill_openhuman_memory_tree',
    },
    "openviking": {
        "core": '火山引擎上下文数据库/RAGFS三级/24.2k⭐',
        "tags": ['数据库', '上下文', 'RAG', '火山'],
        "scenes": ['上下文数据库'],
        "module": 'skill_openviking',
    },
    "p7_perception": {
        "core": 'GA感知层引擎/P7/ASRSensor+VisionSensor',
        "tags": ['GA', '感知', '传感器', '音频'],
        "scenes": ['GA感知层'],
        "module": 'skill_p7_perception',
    },
    "pdf_template_engine": {
        "core": 'PDF模板引擎，数据分离+多模板，reportlab',
        "tags": ['pdf', '模板', 'reportlab'],
        "scenes": ['批量生成PDF', 'PDF模板复用'],
        "module": 'skill_pdf_template_engine',
    },
    "pipecat": {
        "core": '实时语音多模态/12.4k⭐/30服务商/WebRTC',
        "tags": ['语音', '多模态', '实时', 'agent'],
        "scenes": ['实时语音Agent'],
        "module": 'skill_pipecat',
    },
    "pixelle_video": {
        "core": '18.6k⭐ AI全自动短视频引擎/ComfyUI',
        "tags": ['视频', 'AI', '自动', 'ComfyUI'],
        "scenes": ['短视频自动生成'],
        "module": 'skill_pixelle_video',
    },
    "playwright_mcp": {
        "core": 'Playwright MCP浏览器自动化/32.8k⭐',
        "tags": ['MCP', '浏览器', 'playwright', '自动化'],
        "scenes": ['MCP浏览器自动化'],
        "module": 'skill_playwright_mcp',
    },
    "prompt_engineering_advanced": {
        "core": '高级提示工程/思维链/结构化输出/自洽性推理',
        "tags": ['prompt', '提示', '工程', '思维链', '高级'],
        "scenes": ['高级Prompt设计', '思维链优化', '结构化输出'],
        "module": 'skill_prompt_engineering_advanced',
    },
    "promptfoo": {
        "core": 'LLM评估红队/21.4k⭐/OpenAI收购',
        "tags": ['评估', '红队', 'LLM', '安全'],
        "scenes": ['LLM评估测试'],
        "module": 'skill_promptfoo',
    },
    "quant_feature_engineering": {
        "core": '量化特征工程：防未来函数/分层离散化/时序特征',
        "tags": ['量化', '金融', '特征工程', '回测'],
        "scenes": ['构建量化因子', '避免未来函数'],
        "module": 'skill_quant_feature_engineering',
    },
    "quant_moe_rl": {
        "core": 'MoE混合专家+Gate路由',
        "tags": ['量化', 'MoE', '混合专家', 'RL'],
        "scenes": ['MoE交易模型', '混合专家策略'],
        "module": 'skill_quant_moe_rl',
    },
    "quant_risk_execution": {
        "core": '量化风控6层体系',
        "tags": ['量化', '风控', '金融', '交易'],
        "scenes": ['量化风控', '交易风险控制'],
        "module": 'skill_quant_risk_execution',
    },
    "quant_trading_env": {
        "core": 'RL交易环境/四重约束',
        "tags": ['量化', '强化学习', '交易', 'RL'],
        "scenes": ['RL交易环境', '强化学习交易'],
        "module": 'skill_quant_trading_env',
    },
    "quant_walk_forward": {
        "core": 'Walk-Forward验证：四级判定/过拟合检测',
        "tags": ['量化', '回测', '过拟合', '验证'],
        "scenes": ['策略回测验证'],
        "module": 'skill_quant_walk_forward_validation',
    },
    "qwen3_vl": {
        "core": '视觉语言模型/19.2k⭐/Visual Agent/OCR',
        "tags": ['视觉', 'LLM', 'OCR', '多模态'],
        "scenes": ['视觉语言模型'],
        "module": 'skill_qwen3_vl',
    },
    "ralph": {
        "core": '19k⭐ 自治Agent循环/PRD驱动/文件持久化',
        "tags": ['agent', '自治', 'PRD', '持久化'],
        "scenes": ['自治Agent开发'],
        "module": 'skill_ralph',
    },
    "same_as_ever_perspective": {
        "core": 'Morgan Housel/15条不变法则',
        "tags": ['思维', '投资', 'housel', '不变'],
        "scenes": ['长期思维', '不变法则'],
        "module": 'skill_same_as_ever_perspective',
    },
    "second_provider_deepseek_reasoner": {
        "core": 'DeepSeek冗余接入/零成本双模型',
        "tags": ['deepseek', '推理', '冗余', '轮换'],
        "scenes": ['DeepSeek接入'],
        "module": 'skill_second_provider_deepseek_reasoner',
    },
    "socrates_perspective": {
        "core": '问题即答案/追问勇气/三层Agent内化',
        "tags": ['思维', '哲学', '苏格拉底', '追问'],
        "scenes": ['哲学思考', '批判性思维'],
        "module": 'skill_socrates_perspective',
    },
    "superagent": {
        "core": 'AI安全SDK/6.6k⭐/Guard防注入/MCP集成',
        "tags": ['安全', 'SDK', '防注入', 'MCP'],
        "scenes": ['AI安全防护'],
        "module": 'skill_superagent',
    },
    "thinking_frameworks": {
        "core": '三大思维框架：第一性原理/决策矩阵/Premortem/知行间隙，10模块精读',
        "tags": ['商业', 'strategy', 'business', '思维', '方法论', '决策', '分析'],
        "scenes": ['商业分析', '决策分析', '复杂问题分析', '风险预判', '决策对比', '战略规划'],
        "module": 'skill_thinking_frameworks_3pack',
    },
    "thinking_frameworks_3pack": {
        "core": '三大思维框架/10模块/可直接发货',
        "tags": ['思维', '决策', '方法论', '框架'],
        "scenes": ['思维框架应用'],
        "module": 'skill_thinking_frameworks_3pack',
    },
    "tmwebdriver_sop": {
        "core": '浏览器高级操作：文件上传/图搜/PDF blob/物理坐标/Cookie',
        "tags": ['浏览器', '文件上传', '图搜', 'Cookie'],
        "scenes": ['需要上传文件到网页', '通过图片搜索', '操作HttpOnly Cookie'],
        "module": 'tmwebdriver_sop',
    },
    "top5_project_insights": {
        "core": '5大超级项目融合/TOP5内化模式',
        "tags": ['项目', '融合', '内化', 'TOP5'],
        "scenes": ['项目融合', '内化模式'],
        "module": 'skill_top5_project_insights',
    },
    "ui_tars": {
        "core": 'bytedance 34.9k⭐多模态GUI Agent/VLM',
        "tags": ['GUI', '多模态', 'VLM', '视觉'],
        "scenes": ['GUI Agent操作'],
        "module": 'skill_ui_tars',
    },
    "vision_sop": {
        "core": '视觉检测SOP：窗口截图/图像分析/UI识别',
        "tags": ['视觉', '截图', '识别', 'vision', 'screen', 'image'],
        "scenes": ['窗口截图', '图像分析', '视觉识别'],
        "module": 'vision_sop',
    },
    "voxcpm": {
        "core": '19k⭐ 多语言TTS/Voice Design/30语言',
        "tags": ['TTS', '语音', '多语言', '音频'],
        "scenes": ['语音合成'],
        "module": 'skill_voxcpm',
    },
    "web_setup_sop": {
        "core": 'Web工具链初始化，CDP桥接扩展安装与验证',
        "tags": ['浏览器', 'CDP', '扩展', 'web工具'],
        "scenes": ['浏览器不可用时初始化'],
        "module": 'web_setup_sop',
    },
    "wechat_official_account": {
        "core": '微信公众号运营/排版/增长策略/数据分析',
        "tags": ['公众号', '微信', '运营', '内容', '增长'],
        "scenes": ['公众号运营', '微信运营', '公众号排版'],
        "module": 'skill_wechat_oa',
    },
    "whisper_cpp": {
        "core": '50k⭐ Whisper C++移植/GGML/离线安卓',
        "tags": ['语音', 'ASR', 'whisper', 'C++'],
        "scenes": ['离线语音识别'],
        "module": 'skill_whisper_cpp',
    },
    "xiaohongshu_pdf": {
        "core": '小红书笔记PDF生成器，6页标准版，simhei黑体，浅色模板',
        "tags": ['pdf', '小红书', 'reportlab', '设计'],
        "scenes": ['生成小红书风格PDF'],
        "module": 'skill_xiaohongshu_pdf_generator',
    },
    "xixi_daemon": {
        "core": '嘻嘻自主守护进程/3任务心跳/GBK限制',
        "tags": ['GA', '守护', '心跳', '自检'],
        "scenes": ['GA守护进程'],
        "module": 'skill_xixi_daemon',
    },
    "zhihu_content": {
        "core": '知乎内容创作/问答策略/高赞技巧/知乎运营',
        "tags": ['知乎', '内容', '问答', '运营'],
        "scenes": ['知乎回答', '知乎文章', '知乎运营'],
        "module": 'skill_zhihu_content',
    },
    "技能注册表——按需匹配，只加载Top-3browser_use": {
        "core": '浏览器自动化，三步循环(感知-决策-执行)+双模感知+声明式动作',
        "tags": ['浏览器', '自动化', '爬虫', '网页', 'search'],
        "scenes": ['搜索GitHub项目', '爬取网页数据', '浏览器测试'],
        "module": 'browser_use_bridge',
    },
}
